edition = "2018"
fn_single_line = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true

